In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

%matplotlib inline

In [2]:
fba = pd.read_csv('../result/fba_abs.csv', index_col=0)

In [3]:
for i in fba.columns:
    for l in fba.index:
        if fba[i][l] == 0:
            fba = fba.drop(l)

In [4]:
fba

                       Control   Clone A   Clone B
BIOMASS               0.001803  0.003173  0.002333
R00200               -0.014733 -0.071747 -0.038218
R00268                0.002674  0.004707  0.003461
R00341               -0.003814 -0.006713 -0.004936
R00342                0.000648  0.001140  0.000838
R00351               -0.002674 -0.004707 -0.003461
R00658                0.018547  0.078460  0.043154
R00703               -0.011147 -0.065436 -0.033577
R01015               -0.010194 -0.040849 -0.022768
R01049                0.000232  0.000408  0.000300
R01056               -0.000155 -0.000272 -0.000200
R01061                0.020310  0.081563  0.045436
R01070                0.010194  0.040849  0.022768
R01082               -0.000648 -0.001140 -0.000838
R01196               -0.002674 -0.004707 -0.003461
R01325                0.002674  0.004707  0.003461
R01512               -0.020310 -0.081563 -0.045436
R01518               -0.018547 -0.078460 -0.043154
R01529               -0.000155 -0.000272 -0.000200
R01641                0.000077  0.000136  0.000100
R01786                0.010767  0.041859  0.023510
R01830                0.000077  0.000136  0.000100
R01899                0.002674  0.004707  0.003461
R01900               -0.002674 -0.004707 -0.003461
R02740                0.010271  0.040985  0.022868
R04779                0.010194  0.040849  0.022768
Glucose_input         0.010767  0.041859  0.023510
Oxygen_input          0.009948  0.017510  0.012875
CO2_output            0.010836  0.019072  0.014024
Lactate_output        0.011147  0.065436  0.033577
Ammonia_input         0.000648  0.001140  0.000838
acetyl_CoA_hydrolase -0.000084 -0.000148 -0.000109
NADP_Exchange         0.008323  0.014650  0.010772
ADP_Exchange          0.026073  0.091706  0.052895
AMP_Exchange          0.000232  0.000408  0.000300
R08575               -0.000077 -0.000136 -0.000100
Oxophos               0.009948  0.017510  0.012875

In [5]:
fba.loc[['BIOMASS', 'Glucose_input','Oxygen_input', 'Lactate_output', 'Ammonia_input']]

                 Control   Clone A   Clone B
BIOMASS         0.001803  0.003173  0.002333
Glucose_input   0.010767  0.041859  0.023510
Oxygen_input    0.009948  0.017510  0.012875
Lactate_output  0.011147  0.065436  0.033577
Ammonia_input   0.000648  0.001140  0.000838

In [6]:
t = (fba.T/fba['Control']).T

In [11]:
t

                      Control   Clone A   Clone B
BIOMASS                   1.0  1.760117  1.294255
R00200                    1.0  4.869724  2.594007
R00268                    1.0  1.760117  1.294255
R00341                    1.0  1.760117  1.294255
R00342                    1.0  1.760117  1.294255
R00351                    1.0  1.760117  1.294255
R00658                    1.0  4.230314  2.326747
R00703                    1.0  5.870009  3.012105
R01015                    1.0  4.007345  2.233550
R01049                    1.0  1.760117  1.294255
R01056                    1.0  1.760117  1.294255
R01061                    1.0  4.015895  2.237124
R01070                    1.0  4.007345  2.233550
R01082                    1.0  1.760117  1.294255
R01196                    1.0  1.760117  1.294255
R01325                    1.0  1.760117  1.294255
R01512                    1.0  4.015895  2.237124
R01518                    1.0  4.230314  2.326747
R01529                    1.0  1.760117  1.294255
R01641                    1.0  1.760117  1.294255
R01786                    1.0  3.887681  2.183533
R01830                    1.0  1.760117  1.294255
R01899                    1.0  1.760117  1.294255
R01900                    1.0  1.760117  1.294255
R02740                    1.0  3.990439  2.226483
R04779                    1.0  4.007345  2.233550
Glucose_input             1.0  3.887681  2.183533
Oxygen_input              1.0  1.760117  1.294255
CO2_output                1.0  1.760117  1.294255
Lactate_output            1.0  5.870009  3.012105
Ammonia_input             1.0  1.760117  1.294255
acetyl_CoA_hydrolase      1.0  1.760117  1.294255
NADP_Exchange             1.0  1.760117  1.294255
ADP_Exchange              1.0  3.517300  2.028721
AMP_Exchange              1.0  1.760117  1.294255
R08575                    1.0  1.760117  1.294255
Oxophos                   1.0  1.760117  1.294255

In [9]:
for i in t[np.abs(t['Clone A']) > 2].index:
    print(i, '#4682b4')

R00200 #4682b4
R00658 #4682b4
R00703 #4682b4
R01015 #4682b4
R01061 #4682b4
R01070 #4682b4
R01512 #4682b4
R01518 #4682b4
R01786 #4682b4
R02740 #4682b4
R04779 #4682b4
Glucose_input #4682b4
Lactate_output #4682b4
ADP_Exchange #4682b4

In [10]:
for i in sorted(list(set(t.index)-set(t[np.abs(t['Clone A']) > 2].index))):
    print(i, '#b0c4de')

AMP_Exchange #b0c4de
Ammonia_input #b0c4de
BIOMASS #b0c4de
CO2_output #b0c4de
NADP_Exchange #b0c4de
Oxophos #b0c4de
Oxygen_input #b0c4de
R00268 #b0c4de
R00341 #b0c4de
R00342 #b0c4de
R00351 #b0c4de
R01049 #b0c4de
R01056 #b0c4de
R01082 #b0c4de
R01196 #b0c4de
R01325 #b0c4de
R01529 #b0c4de
R01641 #b0c4de
R01830 #b0c4de
R01899 #b0c4de
R01900 #b0c4de
R08575 #b0c4de
acetyl_CoA_hydrolase #b0c4de