In [45]:
import pandas as pd
import numpy as np
import re

In [46]:
t = pd.read_csv('../csv/minimum_reaction.csv').dropna().drop_duplicates().sort_values('Reaction Number').reset_index(drop=True)

In [47]:
f = []
g = []
for i in t['Compound Number']:
    f.append([x for x in (i.replace("+", "")).split(' ') if x])
    g.extend([x for x in (i.replace("+", "")).replace("<=>", "").split(' ') if x])
    
g = pd.DataFrame(list(set(g)))
g.columns = ['c']
g = g.sort_values('c').reset_index(drop=True).drop(0)

In [48]:
df = pd.DataFrame(
    index=list(t['Reaction Number']), 
    columns=list(g['c']))

In [94]:
for i, j in enumerate(df.index):
    num = 1
    sign = -1
    for p in f[i]:
        if p.isdecimal():
            num = p
        elif p == '<=>':
            sign = 1
        
        if p[0] == 'C':
            df[p][j] = num*sign
            num = 1

In [95]:
# num = 1
# sign = -1
# for p in n['R01196']:
#     if p.isdecimal():
#         num = p
#         print('fffffff')
#     elif p == '<=>':
#         sign = 1
#     if p[0] == 'C':
#         print(num*sign)
#         num = 1

In [96]:
df.T['R01196'].dropna()['C00080']

''

In [97]:
n = pd.DataFrame(f, index=list(t['Reaction Number'])).T

In [98]:
print(n['R01196'])

0          2
1     C00138
2     C00024
3     C00011
4          2
5     C00080
6        <=>
7          2
8     C00139
9     C00022
10    C00010
Name: R01196, dtype: object

In [69]:
n

,R00014,R00200,R00229,R00235,R00268,R00305,R00341,R00342,R00344,R00351,...,R09532,R09780,R10221,R10324,R10343,R10407,R10408,R10615,R10860,R10907
0,C00022,C00002,C00002,C00002,C05379,C00031,C00002,C00149,C00002,C00158,...,C01159,C06019,C00345,C00577,C00091,C03752,C20589,C00577,C00118,C01172
1,C00068,C00022,C00033,C00033,<=>,C15602,C00036,C00003,C00022,C00010,...,C00001,<=>,C00003,C00001,C00033,C04261,<=>,C00006,C00003,C00003
2,<=>,<=>,C00010,C00010,C00026,<=>,<=>,<=>,C00288,<=>,...,<=>,C05345,<=>,C00028,<=>,<=>,C04442,C00001,C00001,<=>
3,C05125,C00008,<=>,<=>,C00011,C00198,C00008,C00036,<=>,C00024,...,C00631,None,C00199,<=>,C00024,C20589,C00014,<=>,<=>,C01236
4,C00011,C00074,C00008,C00020,None,C15603,C00074,C00004,C00008,C00001,...,C00009,None,C00011,C00258,C00042,C00615,None,C00258,C00197,C00004
5,None,None,C00024,C00013,None,None,C00011,C00080,C00009,C00036,...,None,None,C00004,C00030,None,None,None,C00005,C00004,C00080
6,None,None,C00009,C00024,None,None,None,None,C00036,None,...,None,None,C00080,None,None,None,None,C00080,C00080,None
7,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
8,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
9,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
10,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None